
CREATE TABLE STUDENT(                       
    Stu_ID VARCHAR(20),
    S_Status ENUM('proper', 'repeat', 'suspended'),
    Dep_ID VARCHAR(20), 
    PRIMARY KEY(Stu_ID)
);


CREATE TABLE USER(                         
    User_Id VARCHAR(20),
    NIC CHAR(20) UNIQUE,
    F_name VARCHAR(50),
    L_name VARCHAR(50),
    DOB DATE,
    Gender VARCHAR(10),
    `Address` VARCHAR(50),
    Contact_no VARCHAR(20),
    Email VARCHAR(50),
    `Role` ENUM('STUDENT', 'LECTURER', 'DEAN', 'TO','ADMIN') NOT NULL,
    PRIMARY KEY(User_Id)
);

CREATE TABLE ADMIN (
    ADMIN_ID VARCHAR(20),
    Dep_ID VARCHAR(20),
    PRIMARY KEY(ADMIN_ID),
    FOREIGN KEY(ADMIN_ID) REFERENCES USER(User_Id)
);

CREATE TABLE ATTENDENCE (
   Course_ID VARCHAR(20),
   Stu_ID VARCHAR(20),
   A_Status VARCHAR(20),
   A_DATE DATE,
   A_Type VARCHAR(20),
   DEAN_ID VARCHAR(20),
   PRIMARY KEY (Course_ID, Stu_ID, A_DATE, A_Type)
);

CREATE TABLE DEPARTMENT(
     Dep_ID  VARCHAR(20),
     D_Name VARCHAR(50),
     DEAN_ID VARCHAR(20),
     ADMIN_ID VARCHAR(20),
     PRIMARY KEY(Dep_ID)
);

CREATE TABLE LECTURER(
      LEC_ID   VARCHAR(20),
      Position VARCHAR(50),
      Dep_ID VARCHAR(20),
      PRIMARY KEY(LEC_ID),
      FOREIGN KEY(LEC_ID) REFERENCES USER(User_Id) ON DELETE CASCADE
);

CREATE TABLE COURSE_UNIT(
    Course_ID VARCHAR(20) PRIMARY KEY,
    C_Name VARCHAR(50),
    Credit INT,
	C_Type VARCHAR(50),
    Dep_ID VARCHAR(20)
);

CREATE TABLE ELIGIBILITY (
    ELI_ID VARCHAR(20) PRIMARY KEY,
    E_Status varchar(25)
);



CREATE TABLE DEAN(
    DEAN_ID VARCHAR(20),
    PRIMARY KEY(DEAN_ID),
    FOREIGN KEY(DEAN_ID) REFERENCES USER(User_Id) ON DELETE CASCADE
);

CREATE TABLE TECHNICAL_OFFICER(
	TO_ID VARCHAR(20),
	T_Role VARCHAR(50),
	PRIMARY KEY(TO_ID),
	FOREIGN KEY(TO_ID) REFERENCES USER(User_Id) ON DELETE CASCADE
);

CREATE TABLE EXAM_MARK(
	Stu_ID VARCHAR(20),
	Course_ID VARCHAR(20),
	Quiz_1 DECIMAL(5,2),
	Quiz_2 DECIMAL(5,2),
	Quiz_3 DECIMAL(5,2),
	Assesment DECIMAL(5,2),
	mid_Theory DECIMAL(5,2),
	mid_Practical DECIMAL(5,2),
	end_Theory DECIMAL(5,2),
	end_Practical DECIMAL(5,2),
	PRIMARY KEY(Stu_ID, Course_ID)
);

CREATE TABLE MEDICAL(
 	MED_ID VARCHAR(20),
 	STU_ID VARCHAR(20),
 	Course_ID VARCHAR(20),
 	M_Description VARCHAR(50),
	SubmitDate  DATE,
 	PRIMARY KEY(Med_ID)
);

CREATE TABLE LECTURER_COURSE(
 	LEC_ID VARCHAR(20),
 	COURSE_ID VARCHAR(20),
 	Lec_in_charge VARCHAR(50),
 	Lec_hours DECIMAL(5,2),
 	PRIMARY KEY(LEC_ID, Course_ID)
);

CREATE TABLE LECTURER_STUDENT(
 	LEC_ID VARCHAR(20),
 	Stu_ID VARCHAR(20),
 	PRIMARY KEY(LEC_ID, Stu_ID)
);

CREATE TABLE STUDENT_COURSE(
    Stu_ID VARCHAR(20),
    COURSE_ID VARCHAR(20),
    PRIMARY KEY(Stu_ID, Course_ID)
);

CREATE TABLE STUDENT_ELIGIBILITY(
    Stu_ID VARCHAR(20),
    Course_ID VARCHAR(20),
	CA_marks DECIMAL(5, 2),
	Attendance_percentage DECIMAL(5, 2),
	Eligibility_status VARCHAR(20),
    PRIMARY KEY(Stu_ID, Course_ID)
);
