
--Student table
ALTER TABLE STUDENT
ADD FOREIGN KEY(Stu_ID) REFERENCES USER(User_Id);

ALTER TABLE STUDENT
ADD FOREIGN KEY(Dep_ID) REFERENCES DEPARTMENT(Dep_ID);




--Admin table
ALTER TABLE ADMIN 
ADD FOREIGN KEY(Dep_ID) REFERENCES DEPARTMENT(Dep_ID);



--Attendence table
ALTER TABLE ATTENDENCE
ADD FOREIGN KEY(Course_ID) REFERENCES COURSE_UNIT(Course_ID);

ALTER TABLE ATTENDENCE
ADD FOREIGN KEY(Stu_ID) REFERENCES STUDENT(Stu_Id); 

ALTER TABLE ATTENDENCE
ADD FOREIGN KEY(DEAN_ID) REFERENCES DEAN(DEAN_Id);



--Department table
ALTER TABLE DEPARTMENT
ADD FOREIGN KEY(DEAN_ID) REFERENCES DEAN(DEAN_ID);

ALTER TABLE DEPARTMENT
ADD FOREIGN KEY(ADMIN_ID) REFERENCES ADMIN(ADMIN_ID);



--Lecturer table
ALTER TABLE LECTURER
ADD FOREIGN KEY(Dep_ID) REFERENCES DEPARTMENT(Dep_ID);



--Course unit table
ALTER TABLE COURSE_UNIT
ADD FOREIGN KEY(Dep_ID) REFERENCES DEPARTMENT(Dep_ID);



--Student course table
ALTER TABLE STUDENT_COURSE
ADD FOREIGN KEY(Stu_ID) REFERENCES STUDENT(Stu_ID);

ALTER TABLE STUDENT_COURSE
ADD FOREIGN KEY(COURSE_ID) REFERENCES COURSE_UNIT(Course_ID);



--Ezam mark table
ALTER TABLE EXAM_MARK
ADD FOREIGN KEY(Stu_ID) REFERENCES STUDENT(Stu_ID);

ALTER TABLE EXAM_MARK
ADD FOREIGN KEY(Course_ID) REFERENCES COURSE_UNIT(Course_ID);




--Medical table
ALTER TABLE MEDICAL
ADD FOREIGN KEY(STU_ID) REFERENCES STUDENT(Stu_ID);

ALTER TABLE MEDICAL
ADD FOREIGN KEY(Course_ID) REFERENCES COURSE_UNIT(Course_ID);



--Lecturer course table
ALTER TABLE LECTURER_COURSE
ADD FOREIGN KEY(LEC_ID) REFERENCES LECTURER(LEC_ID);

ALTER TABLE LECTURER_COURSE
ADD FOREIGN KEY(COURSE_ID) REFERENCES COURSE_UNIT(Course_ID);



--Lecturer student table
ALTER TABLE LECTURER_STUDENT
ADD FOREIGN KEY(LEC_ID) REFERENCES LECTURER(LEC_ID);  

ALTER TABLE LECTURER_STUDENT
ADD FOREIGN KEY(Stu_ID) REFERENCES STUDENT(Stu_ID);


--Student_Eligibility TABLE
ALTER TABLE STUDENT_ELIGIBILITY 
ADD FOREIGN KEY(Stu_ID) REFERENCES STUDENT(Stu_ID);

ALTER TABLE STUDENT_ELIGIBILITY 
ADD FOREIGN KEY(Course_ID) REFERENCES COURSE_UNIT(Course_ID);

