
--Exam_Mark Table

ALTER TABLE EXAM_MARK
ADD FOREIGN KEY(Stu_ID) REFERENCES STUDENT(Stu_ID);

ALTER TABLE EXAM_MARK
ADD FOREIGN KEY(Course_ID) REFERENCES COURSE_UNIT(Course_ID);

ALTER TABLE EXAM_MARK
ADD FOREIGN KEY(ELI_ID) REFERENCES ELIGIBILITY(ELI_ID);





--Medical Table

ALTER TABLE MEDICAL
ADD FOREIGN KEY(STU_ID) REFERENCES STUDENT(Stu_ID);

ALTER TABLE MEDICAL
ADD FOREIGN KEY(Course_ID) REFERENCES COURSE_UNIT(Course_ID);

ALTER TABLE MEDICAL
ADD FOREIGN KEY(TO_ID) REFERENCES TECHNICAL_OFFICER(TO_ID);





--LECTURER_COURSE Table

ALTER TABLE LECTURER_COURSE
ADD FOREIGN KEY(LEC_ID) REFERENCES LECTURER(LEC_ID);

ALTER TABLE LECTURER_COURSE
ADD FOREIGN KEY(COURSE_ID) REFERENCES COURSE_UNIT(Course_ID);





--LECTURER_STUDENT Table

ALTER TABLE LECTURER_STUDENT
ADD FOREIGN KEY(LEC_ID) REFERENCES LECTURER(LEC_ID);  

ALTER TABLE LECTURER_STUDENT
ADD FOREIGN KEY(Stu_ID) REFERENCES STUDENT(Stu_ID);