
--COURSE_UNIT Table

ALTER TABLE COURSE_UNIT
ADD FOREIGN KEY(Dep_ID) REFERENCES DEPARTMENT(Dep_ID);



--STUDENT_COURSE Table

ALTER TABLE STUDENT_COURSE
ADD FOREIGN KEY(Stu_ID) REFERENCES STUDENT(Stu_ID);

ALTER TABLE STUDENT_COURSE
ADD FOREIGN KEY(COURSE_ID) REFERENCES COURSE_UNIT(Course_ID);