CREATE TABLE COURSE_UNIT(
    Course_ID VARCHAR(20) PRIMARY KEY,
    Course_Name VARCHAR(50),
    Course_Credit INT,
    DepID VARCHAR(20)
);

CREATE TABLE ELIGIBILITY (
    ELI_ID VARCHAR(20) PRIMARY KEY,
    E_Status varchar(25),
    StuID varchar(10)
);

CREATE TABLE STUDENT_COURSE(
    Stu_ID VARCHAR(20),
    COURSE_ID VARCHAR(20),
    PRIMARY KEY(Stu_ID, Course_ID)
);

