
-- ADMIN Table structure


CREATE TABLE ADMIN (                            

    ADMIN_ID VARCHAR(20),
    Dep_ID VARCHAR(20), 

    PRIMARY KEY(ADMIN_ID),

    FOREIGN KEY(ADMIN_ID) REFERENCES USER(User_Id),
    FOREIGN KEY(Dep_ID) REFERENCES DEPARTMENT(Dep_ID)

);